#
# $Copyright Open Broadcom Corporation$
#

obj-$(CONFIG_IPROC_PWM) += pwm/
obj-$(CONFIG_IPROC_GPIO) += gpio/
obj-$(CONFIG_IPROC_I2C) += i2c/
obj-$(CONFIG_USB_EHCI_IPROC) += usb/
obj-$(CONFIG_IPROC_PCIE) += pci/

