#
# (C) Copyright 2002-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += flash.o i2c.o memory.o rtc.o
obj-$(CONFIG_IPROC_BOARD_DIAGS) += QSPI_diags.o GPIO_AON_diags.o GPIO_diags.o
obj-$(CONFIG_IPROC_BOARD_DIAGS) += PWM_diags.o
obj-$(CONFIG_IPROC_BOARD_DIAGS) += eMMC_diags.o MMC_diags.o NAND_diags.o
obj-$(CONFIG_IPROC_BOARD_DIAGS) += KEYPAD_diags.o KBD_diags.o
obj-$(CONFIG_IPROC_BOARD_DIAGS) += LCD_diags.o LCD_diags_full_shrek.o
obj-$(CONFIG_IPROC_BOARD_DIAGS) += AUDIO_diags.o
obj-$(CONFIG_IPROC_BOARD_DIAGS) += TDM_diags.o
obj-$(CONFIG_IPROC_BOARD_DIAGS) += USB20_diags.o usb2_loopback.o
obj-$(CONFIG_IPROC_BOARD_DIAGS) += TOUCHSCREEN_diags.o
obj-$(CONFIG_IPROC_BOARD_DIAGS) += spi_diags.o
obj-$(CONFIG_IPROC_BOARD_DIAGS) += UART_diags.o
obj-$(CONFIG_IPROC_BOARD_DIAGS) += PCIE_diags.o
obj-$(CONFIG_IPROC_BOARD_DIAGS) += SPDIF_diags.o
obj-$(CONFIG_IPROC_BOARD_DIAGS) += AMACSWITCH_diags.o
